[env:ES3C28P]
extends = env
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.partitions = custom_16Mb.csv
extra_scripts = 
    pre:patch_library_conflicts.py
    pre:patch.py
    pre:pre_build_current_year.py
lib_ignore = 
    FastLED
; --- DODAJ TĘ LINIĘ TUTAJ ---
build_unflags = 
    -flto
; ---------------------------
build_flags =
    ${env.build_flags}
    -Iboards/ES3C28P
    -UFP
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -DILI9341_DRIVER=1
    -DUSE_TFT_eSPI_TOUCH=1
    -DTFT_MISO=13
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_BL=5
    -DTOUCH_CS=14
