[env:ES3C28P]
extends = env
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.flash_mode = dio
; N16R8 = 16MB flash + 8MB OPI PSRAM. Jesli masz PSRAM QSPI (2MB/4MB), zmien na qio_qspi
board_build.arduino.memory_type = qio_opi
board_build.partitions = custom_16Mb.csv

extra_scripts =
    pre:patch.py
    pre:pre_build_current_year.py
    pre:gen_mqjs_headers.py
    pre:patch_library_conflicts.py
    post:build.py

lib_ignore =
    FastLED

build_unflags =
    -flto

build_src_filter =
    ${env.build_src_filter}
    +<../boards/ES3C28P>

build_flags =
    ${env.build_flags}
    -Iboards/ES3C28P
    -UFP
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -DILI9341_DRIVER=1
    -DUSE_TFT_eSPI_TOUCH=1
    -DTFT_MISO=13
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_BL=5
    -DTOUCH_CS=14
